spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipes?useSSL=false
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none   # keep as-is
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Add these two lines to prevent automatic naming conversion
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
